name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./proc2
        shell: cmd
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: build the application
      run: go build
    
    - name: Test the application
      run: go run . < test_input.txt
